trigger:
  batch: true
  branches:
    include:
      - '*'
    exclude:
      - refs/tags/*

jobs:
  - template: cicd/templates/build-component.job.yml
    parameters:
      componentName: Foo
      subPath: services/foo
      stepsTemplate: services/foo/build.yml
