jobs:
  - job: build_foo
    dependsOn: check_update_status_for_foo
    condition: and(succeeded(), eq(dependencies.check_update_status_for_foo.outputs['fooupdated'], 'true'))
    steps:
      - bash: |
          docker build . -t foo:$(git rev-list -1 HEAD)
        workingDirectory: services/foo
