parameters:
  projectName: ''

jobs:
  - job: ${{ format('check_update_status_for_{0}', parameters.projectName) }}
    displayName: ${{ format('Check update status for {0}', parameters.projectName )}}
    steps:
      - task: ShellScript@2
        name: ${{ parameters.projectName }}
        displayName: Check update status
        inputs:
          scriptPath: cicd/scripts/check-update-status.sh
          args: '${{ parameters.projectName }}'
