parameters:
  projectName: ''

jobs:
  - job: ${{ format('tag_build_{0}', parameters.projectName) }}
    pool:
      vmImage: 'ubuntu-16.04'
    displayName: ${{ format('Tag Build {0}', parameters.projectName )}}
    dependsOn: build_foo
    condition: succeeded()
    steps:
      - checkout: self
        persistCredentials: true
        fetchDepth: 1
      - bash: |
          git tag build-$PROJECT_NAME-$BUILD_BUILDID
          git push --tags
        displayName: Tag build
        env:
          PROJECT_NAME: ${{ parameters.projectName }}
